#!/usr/bin/env python

# Import smtplib for the actual sending function
import smtplib

# Import the email modules we'll need
from email.mime.text import MIMEText


def sendMessage(meAddr, youAddr, textfile):

	# Open a plain text file for reading.  For this example,
	# assume that the text file contains only ASCII characters.
	fp = open(textfile, 'rb')
	# Create a text/plain message
	msg = MIMEText(fp.read())
	fp.close()

	# meAddr == the sender's email address
	# youAddr == the recipient's email address
	msg['Subject'] = 'The contents of %s' % textfile
	msg['From'] = meAddr
	msg['To'] = youAddr

	# Send the message via our own SMTP server, but don't include the
	# envelope header.
	s = smtplib.SMTP('localhost')
	s.sendmail(meAddr, [youAddr], msg.as_string())
	s.quit()



sendMessage("andrew@qemg.org", "ahamiltonwright@mta.ca", "message.txt")

