#!/bin/sh

#
# Demonstrates some interesting argument handling techniques.
# Try running as:
#	listarguments -a one two three "1 2 3"
#

# the construction "$@" expands the argument list
# "as though each argument was in quotes"
echo '$@='"$@"

echo "Printing arguments individually:"
for arg in "$@"
do
	echo '  ${arg}: '${arg}
done

# shift moves the argument list up by one, getting rid of the old argv[1]
echo "shifting..."
shift

echo '$@='"$@"

echo "shifting again..."
shift


echo '$@='"$@"
echo "Printing individually again:"
for arg in "$@"
do
	echo "  [${arg}]"
done

echo "Not really what we want:"
for arg in $@
do
	echo "  (${arg})"
done

# the construction "$*" expands the argument list "without quotes"
echo '$*='"$*"
echo "Printing with star:"
for arg in $*
do
	echo "  [${arg}]"
done


