#!/usr/bin/env python

import sys

anarray = [ 0, 1, 2, 7, "hi", "there", [ 0, 1, 2 ] ]

print anarray

for item in anarray:
	print item

for item in anarray[2:5]:
	print item

for item in [ 0, 1, "hi", "there" ]:
	print item

