#!/usr/bin/env python

import string, sys

# If no arguments were given, print a helpful message
if len(sys.argv)==1:
	print 'Usage: celsius temp1 temp2 ...'
	sys.exit(0)

# Loop over the arguments
for arg in sys.argv[1:]:
	try:
		fahrenheit = int(arg)
	except ValueError:
		print repr(arg), "not a numeric value"
	else:
		celsius = (fahrenheit-32)*5.0/9.0
		print '%.2fC = %.2fF' % (float(celsius), float(fahrenheit))
