#!/usr/bin/env python

import string, sys

# loop over lines read from stdin,
# calling the loop on each line
# read from the file in a block
# (this is more efficient than
# reading/processing line by line,
# but not so good for interactive
# data processing)

for line in sys.stdin.readlines():
	try: 
		celsius = float(line)
	except ValueError:
		print repr(line), "not a numeric value"
	else:
		fahrenheit = (celsius*9.0/5.0) + 32
		print '%.2fC = %.2fF' % (celsius, fahrenheit)
