#!/usr/bin/env python

import string, sys

# If no arguments were given, print a helpful message
if len(sys.argv)==1:
	print 'Usage: fahrenheit temp1 temp2 ...'
	sys.exit(0)

# Loop over the arguments
for arg in sys.argv[1:]:
	try: 
		celsius = float(arg)
	except ValueError:
		print repr(arg), "not a numeric value"
	else:
		fahrenheit = (celsius*9.0/5.0) + 32
		sys.stdout.write('%3gC = %3gF \t(%dC = %dF)\n' %
				(float(celsius), float(fahrenheit),
				int(celsius+.5), int(fahrenheit+.5)))
