#!/usr/bin/env python

# A simple window system example from
# http://www.pythonware.com/library/tkinter/introduction/hello-tkinter.htm

from Tkinter import *

class App:

	def __init__(self, master):

		frame = Frame(master)

		self.someText = Label(frame, text="Hello, Springfield")
		self.someText.pack(side=BOTTOM)

		self.button = Button(frame, text="QUIT", fg="red", command=frame.quit)
		self.button.pack(side=LEFT)

		self.hi_there = Button(frame, text="Hello", command=self.say_hi)
		self.hi_there.pack(side=LEFT)
		frame.pack()

	def say_hi(self):
		print "hi there, everyone!"

root = Tk()

app = App(root)

root.mainloop()


