#!/usr/bin/env python

# Read lines of information, load into an array of column
# and output in a nice format
#

import sys
import string
import math

nRows = 0
columnName = []
columnData = []
formatWidth = []

# read the first line to start
nameline = sys.stdin.readline()
if len(nameline) <= 0:
	sys.stderr.write("No data found in file\n");
	sys.exit(-1)

# store the name we find
for token in string.split(nameline, ','):
	token = token.strip()
	columnName.append(token)
	columnData.append([])
	formatWidth.append(len(token))


## loop on stdin until we run out of data
line = sys.stdin.readline()
while len(line) > 0:

	nRows = nRows + 1

	# split up by commas
	tokens = string.split(line, ',')
	if len(tokens) > len(columnName):
		sys.stderr.write("%d data values found, but only %d name!"
				% (len(tokens), len(columnName)))

	i = 0
	for token in tokens:
		token = token.strip()
		tokenLength = len(token)
		if formatWidth[i] < tokenLength:
			formatWidth[i] = tokenLength

		columnData[i].append(token)
		i = i + 1

	line = sys.stdin.readline()



delimiter = ""
for i in range(0,len(columnName)):
	sys.stdout.write("%s%*s" % (delimiter, formatWidth[i], columnName[i]))
	delimiter = ", "
sys.stdout.write("\n")

for j in range(0,nRows):
	delimiter = ""
	for i in range(0,len(columnName)):
		data = columnData[i][j]
		sys.stdout.write("%s%*s" % (delimiter, formatWidth[i], data))
		delimiter = ", "
	sys.stdout.write("\n")


