#!/usr/bin/env python

import sys
import string

# Print out our arguments

##
def printHelp(progname):

	sepIndex = string.rfind(progname, "/")
	if sepIndex < 0:
		printProgname = progname
	else:
		printProgname = progname[sepIndex + 1:]

	sys.stderr.write("%s <anything>\n" % printProgname)
	sys.stderr.write("\n")
	sys.stderr.write("Print out our arguments!")
	sys.stderr.write("\n")


##
## ----------------------------------------------------------------
## Beginning of mainline
##

def main(argv):
	sawArgument = 0

	for arg in argv[1:]:
		if arg[0] == '-':
			if len(arg) > 1 and (arg[1] == 'h' or arg[1] == 'H'):
				printHelp(argv[0])
				sys.exit(1)

			else:
				sys.stdout.write("Got flag '%s'\n" % arg)
				sawArgument = 1

		else:
			sys.stdout.write("Got arg  '%s'\n" % arg)
			sawArgument = 1

	if sawArgument == 0:
		printHelp(argv[0])

##
## ----------------------------------------------------------------
## This causes the main() function to be called if run from
## the command line; otherwise we can be loaded as an
## importable module
if __name__ == "__main__": main(sys.argv)

