#!/usr/bin/env python

# Template for a Python program using main()

import sys
import string

##
def processFile(ofile, ifile):

	line = ifile.readline()

	if len(line) == 0:
		sys.stderr.write("No data in file\n")
		sys.exit(-1)

	while len(line) > 0:

		tokens = line.split()
		if len(tokens) > 0:
			ofile.write("first token is [%s]\n" % tokens[0])

		line = ifile.readline()


##
def printHelp(progname):

	print progname, "[ <options> ] <input file> [ <input file> ...]"
	print ""
	print "This does something!"
	print ""


##
## ----------------------------------------------------------------
## Beginning of mainline
##

def main(argv):
	ofile = sys.stdout

	## process arguments
	for arg in argv[1:]:
		# handle anything starting with a dash
		if arg[0] == '-':
			if arg[1] == 'h' or arg[1] == 'H':
				printHelp(argv[0])
				sys.exit(1)

			else:
				print "Got argument: ", arg

		else:
			# handle the file arguments
			try:
				ifile = open(arg, "r")
			except IOError, (errno, strerror):
				sys.stderr.write("Failed opening input file '%s'\n" % arg)
				sys.stderr.write("	I/O error(%s) : %s\n" % (errno, strerror))
				sys.stderr.write("\n")
				sys.exit(1)

			processFile(ofile, ifile)
			ifile.close()


##
## ----------------------------------------------------------------
## This causes the main() function to be called if run from
## the command line; otherwise we can be loaded as an
## importable module
if __name__ == "__main__": main(sys.argv)
