#!/usr/bin/env python

import sys

line = sys.stdin.readline()
while len(line) > 0:
	sys.stdout.write("%s\n" % line.split()[0])
	sys.stdout.write("arguments:\n")
	for token in line.split()[1:]:
		sys.stdout.write("[%s]" % token)
	sys.stdout.write("\n")
	line = sys.stdin.readline()

